name: Build Windows Executable

on:
  push:
    branches:
      - main  # Se activa cuando haces un push a la rama main

jobs:
  build:
    runs-on: windows-latest  # Usa una máquina virtual con Windows

    steps:
      # Paso 1: Obtén el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configura JDK 20
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'  # Usa Temurin (OpenJDK)

      # Paso 3: Compila el proyecto con Maven
      - name: Build with Maven
        run: mvn clean package

      # Paso 4: Crea el ejecutable con jpackage
      - name: Create Windows Executable
        run: |
          jpackage --input target/ --name Tareas --main-jar tareas-0.0.1-SNAPSHOT.jar --main-class gm.tareas.TareasApplication --type app-image --dest output

      # Paso 5: Sube el ejecutable como un artefacto
      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: Tareas-Windows-Executable
          path: output/